import { useEffect, useMemo, useState } from "react";
import { ArrowDownUp, List, Map as MapIcon, RotateCcw, Search, SlidersHorizontal, X } from "lucide-react";
import { MapContainer, Marker, Popup, TileLayer } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import L from "leaflet";
import { Link, useSearch } from "wouter";
import { useSiteContent } from "@/data/siteContent";
import { PropertyCard } from "@/components/PropertyCard";
import { localized, usePreferences } from "@/lib/preferences";

delete (L.Icon.Default.prototype as { _getIconUrl?: unknown })._getIconUrl;
L.Icon.Default.mergeOptions({ iconRetinaUrl: "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon-2x.png", iconUrl: "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon.png", shadowUrl: "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-shadow.png" });
const categories = ["الكل", "عمائر للبيع", "شقق للبيع", "شقق للإيجار", "أراضي للبيع"];
const typeOptions = ["all", "شقق", "عمائر", "أراضي"];

export default function Properties() {
  const { data, isLoading, isError, refetch } = useSiteContent();
  const { locale, t } = usePreferences();
  const properties = data?.properties ?? [];
  const search = useSearch();
  const [query, setQuery] = useState(() => new URLSearchParams(window.location.search).get("q") || "");
  const [category, setCategory] = useState("الكل");
  const [neighborhood, setNeighborhood] = useState("الكل");
  const [type, setType] = useState("all");
  const [purpose, setPurpose] = useState("all");
  const [minPrice, setMinPrice] = useState("");
  const [maxPrice, setMaxPrice] = useState("");
  const [minRooms, setMinRooms] = useState("all");
  const [minBathrooms, setMinBathrooms] = useState("all");
  const [minArea, setMinArea] = useState("");
  const [maxArea, setMaxArea] = useState("");
  const [sort, setSort] = useState("latest");
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [view, setView] = useState<"grid" | "map">(() => new URLSearchParams(window.location.search).get("view") === "map" ? "map" : "grid");
  useEffect(() => {
    const params = new URLSearchParams(search);
    setQuery(params.get("q") || "");
    setView(params.get("view") === "map" ? "map" : "grid");
  }, [search]);
  const neighborhoods = [...new Set(properties.map(p => p.neighborhood))];
  const neighborhoodLabel = (value: string) => localized(properties.find(p => p.neighborhood === value)!, "neighborhood", locale);
  const categoryLabel = (value: string) => value === "الكل" ? t("جميع العقارات", "All properties") : localized(properties.find(p => p.type === value) || { type: value, typeEn: ({ "عمائر للبيع": "Buildings for sale", "شقق للبيع": "Apartments for sale", "شقق للإيجار": "Apartments for rent", "أراضي للبيع": "Land for sale" } as Record<string, string>)[value] }, "type", locale);
  const results = useMemo(() => properties.filter(p => {
    const term = query.trim().toLocaleLowerCase();
    const matchText = !term || [p.title, p.titleEn, p.neighborhood, p.neighborhoodEn, p.description, p.descriptionEn].some(value => value?.toLocaleLowerCase().includes(term));
    return matchText && (category === "الكل" || p.type === category) && (neighborhood === "الكل" || p.neighborhood === neighborhood) && (type === "all" || p.type.startsWith(type)) && (purpose === "all" || p.purpose === purpose) && (!minPrice || p.price >= Number(minPrice)) && (!maxPrice || p.price <= Number(maxPrice)) && (minRooms === "all" || p.rooms >= Number(minRooms)) && (minBathrooms === "all" || p.bathrooms >= Number(minBathrooms)) && (!minArea || (p.area > 0 && p.area >= Number(minArea))) && (!maxArea || (p.area > 0 && p.area <= Number(maxArea)));
  }).sort((a, b) => sort === "price-low" ? a.price - b.price : sort === "price-high" ? b.price - a.price : sort === "area-large" ? b.area - a.area : sort === "rooms" ? b.rooms - a.rooms : 0), [properties, query, category, neighborhood, type, purpose, minPrice, maxPrice, minRooms, minBathrooms, minArea, maxArea, sort]);
  const reset = () => { setQuery(""); setCategory("الكل"); setNeighborhood("الكل"); setType("all"); setPurpose("all"); setMinPrice(""); setMaxPrice(""); setMinRooms("all"); setMinBathrooms("all"); setMinArea(""); setMaxArea(""); setSort("latest"); };
  const marker = (label: string) => L.divIcon({ className: "custom-map-marker", html: `<div style="background:#172329;color:#e5c180;padding:7px 12px;border:1px solid #e5c180;font-size:11px;font-weight:700;white-space:nowrap;box-shadow:0 6px 20px #0004">${label.replace(/[<>]/g, "")}</div>`, iconSize: [100, 32], iconAnchor: [50, 16] });
  return <main className="site-shell min-h-[100dvh] flex-1">
    <section className="site-always-dark relative overflow-hidden bg-[#172329] py-20 text-[#f0ebdf] md:py-28"><img src="/hero/drive-02.jpg" alt="" className="absolute inset-0 h-full w-full object-cover opacity-30" /><div className="absolute inset-0 bg-gradient-to-l from-[#172329] via-[#172329]/85 to-[#172329]/50" /><div className="site-container relative"><span className="site-eyebrow">{t("استكشف العروض", "DISCOVER PROPERTIES")}</span><h1 className="site-display mt-6 text-5xl md:text-7xl">{t("عقارات العبنق", "The property collection")}</h1><p className="mt-5 max-w-lg text-sm leading-8 text-[#eee8db]/70">{t("تصفح العقارات المتاحة وابحث حسب ما يناسب احتياجاتك.", "Explore available properties and find the right fit for your needs.")}</p></div></section>
    <div className="site-container py-10 md:py-14">
      <div className="flex flex-col gap-4 border-b border-[var(--line-soft)] pb-8 md:flex-row">
        <div className="relative flex-1"><Search size={18} className="absolute start-4 top-1/2 -translate-y-1/2 text-accent" /><input data-testid="input-property-search" type="search" value={query} onChange={event => setQuery(event.target.value)} aria-label={t("البحث بالكلمات", "Keyword search")} placeholder={t("ابحث بالعنوان أو الحي أو الوصف...", "Search title, district, or description...")} className="site-input h-13 w-full ps-12 pe-4 text-sm" /></div>
        <button type="button" data-testid="button-toggle-filters" aria-expanded={filtersOpen} onClick={() => setFiltersOpen(!filtersOpen)} className="site-outline-button inline-flex h-13 items-center justify-center gap-3 px-6 text-sm font-bold"><SlidersHorizontal size={17} />{t("تصفية متقدمة", "Advanced filters")}{filtersOpen && <X size={15} />}</button>
      </div>
      <div className="mt-6 flex gap-2 overflow-x-auto pb-3">{categories.map(c => <button type="button" key={c} onClick={() => setCategory(c)} aria-pressed={category === c} className={`shrink-0 border px-4 py-2.5 text-xs font-bold transition-colors ${category === c ? "border-accent bg-accent text-accent-foreground" : "border-border text-muted-foreground hover:border-accent hover:text-foreground"}`}>{categoryLabel(c)}</button>)}</div>
      {filtersOpen && <div className="site-card mt-5 p-6 md:p-8"><div className="mb-7 flex items-center justify-between"><h2 className="site-display text-xl">{t("خصص بحثك", "Refine your search")}</h2><button type="button" onClick={reset} className="site-link-arrow"><RotateCcw size={15} />{t("إعادة الضبط", "Reset")}</button></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
        <label className="text-xs font-bold">{t("نوع العقار", "Property type")}<select value={type} onChange={event => setType(event.target.value)} className="site-input mt-2 h-11 w-full px-3"><option value="all">{t("كل الأنواع", "All types")}</option>{typeOptions.slice(1).map((v, i) => <option value={v} key={v}>{[t("شقق", "Apartments"), t("عمائر", "Buildings"), t("أراضي", "Land")][i]}</option>)}</select></label>
        <label className="text-xs font-bold">{t("الحي", "District")}<select value={neighborhood} onChange={event => setNeighborhood(event.target.value)} className="site-input mt-2 h-11 w-full px-3"><option value="الكل">{t("جميع الأحياء", "All districts")}</option>{neighborhoods.map(n => <option value={n} key={n}>{neighborhoodLabel(n)}</option>)}</select></label>
        <label className="text-xs font-bold">{t("نوع العملية", "Transaction")}<select value={purpose} onChange={event => setPurpose(event.target.value)} className="site-input mt-2 h-11 w-full px-3"><option value="all">{t("البيع والإيجار", "Sale and rent")}</option><option value="sale">{t("للبيع", "For sale")}</option><option value="rent">{t("للإيجار", "For rent")}</option></select></label>
        <label className="text-xs font-bold">{t("عدد الغرف الأدنى", "Minimum bedrooms")}<select value={minRooms} onChange={event => setMinRooms(event.target.value)} className="site-input mt-2 h-11 w-full px-3"><option value="all">{t("أي عدد", "Any")}</option>{[2,3,4,5].map(n => <option key={n} value={n}>{n}+</option>)}</select></label>
        <label className="text-xs font-bold">{t("دورات المياه الأدنى", "Minimum bathrooms")}<select value={minBathrooms} onChange={event => setMinBathrooms(event.target.value)} className="site-input mt-2 h-11 w-full px-3"><option value="all">{t("أي عدد", "Any")}</option>{[1,2,3,4].map(n => <option key={n} value={n}>{n}+</option>)}</select></label>
        {[[t("السعر من (ر.س)", "Min price (SAR)"), minPrice, setMinPrice], [t("السعر إلى (ر.س)", "Max price (SAR)"), maxPrice, setMaxPrice], [t("المساحة من (م²)", "Min area (m²)"), minArea, setMinArea], [t("المساحة إلى (م²)", "Max area (m²)"), maxArea, setMaxArea]] .map(([label, value, setter], i) => <label key={i} className="text-xs font-bold">{label as string}<input type="number" min="0" value={value as string} onChange={event => (setter as (v: string) => void)(event.target.value)} className="site-input mt-2 h-11 w-full px-3" /></label>)}
      </div></div>}
      <div className="my-10 flex flex-wrap items-center justify-between gap-5 border-b border-[var(--line-soft)] pb-6"><div><p data-testid="results-count" className="site-display text-2xl">{results.length} {t("عقار متاح", "properties available")}</p><p className="mt-1 text-xs text-muted-foreground">{t(`من أصل ${properties.length} عروض`, `Of ${properties.length} listings`)}</p></div><div className="flex flex-wrap items-center gap-3"><div className="flex border border-border p-1" role="tablist" aria-label={t("طريقة العرض", "View mode")}><button type="button" role="tab" aria-selected={view === "grid"} onClick={() => setView("grid")} className={`flex items-center gap-2 px-3 py-2 text-xs ${view === "grid" ? "bg-accent text-accent-foreground" : "text-muted-foreground"}`}><List size={15} />{t("قائمة", "Grid")}</button><button type="button" role="tab" aria-selected={view === "map"} onClick={() => setView("map")} className={`flex items-center gap-2 px-3 py-2 text-xs ${view === "map" ? "bg-accent text-accent-foreground" : "text-muted-foreground"}`}><MapIcon size={15} />{t("خريطة", "Map")}</button></div><div className="flex items-center gap-2"><ArrowDownUp size={15} className="text-accent" /><select aria-label={t("ترتيب النتائج", "Sort results")} value={sort} onChange={event => setSort(event.target.value)} className="site-input h-10 px-2 text-xs"><option value="latest">{t("الأحدث", "Latest")}</option><option value="price-low">{t("السعر: الأقل", "Price: low to high")}</option><option value="price-high">{t("السعر: الأعلى", "Price: high to low")}</option><option value="area-large">{t("المساحة: الأكبر", "Largest area")}</option><option value="rooms">{t("الغرف: الأكثر", "Most bedrooms")}</option></select></div></div></div>
      {isLoading ? <div className="grid gap-7 md:grid-cols-2 lg:grid-cols-3">{[0,1,2].map(i => <div key={i} className="site-card animate-pulse"><div className="aspect-[4/3] bg-muted" /><div className="space-y-4 p-7"><div className="h-5 w-3/4 bg-muted" /><div className="h-5 w-1/2 bg-muted" /></div></div>)}</div> : isError ? <div role="alert" className="site-card py-20 text-center"><p>{t("تعذر تحميل العقارات.", "Could not load properties.")}</p><button type="button" onClick={() => void refetch()} className="site-button mt-5 px-6 py-3">{t("إعادة المحاولة", "Try again")}</button></div> : view === "grid" ? results.length ? <div data-testid="property-list" className="grid gap-7 md:grid-cols-2 lg:grid-cols-3">{results.map(p => <PropertyCard key={p.id} property={p} />)}</div> : <div data-testid="list-empty-state" className="site-card py-24 text-center"><Search size={30} className="mx-auto text-accent" /><h3 className="site-display mt-6 text-2xl">{t("لم نعثر على عقار بهذه المواصفات", "No properties match these filters")}</h3><p className="mt-3 text-sm text-muted-foreground">{t("جرّب توسيع نطاق البحث أو إعادة ضبط الفلاتر.", "Try broadening your search or resetting your filters.")}</p><button type="button" onClick={reset} className="site-button mt-7 px-6 py-3 text-sm">{t("عرض كل العقارات", "View all properties")}</button></div> : <div data-testid="map-results" className="relative overflow-hidden border border-border"><MapContainer center={[21.3891, 39.8579]} zoom={12} style={{ height: "min(720px,70dvh)", minHeight: "480px", width: "100%" }}><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{results.map(p => <Marker key={p.id} position={p.coordinates} icon={marker(localized(p, "priceLabel", locale))}><Popup className="map-popup-custom"><div className="bg-card text-foreground"><img src={p.image} alt={localized(p, "title", locale)} className="h-32 w-full object-cover" /><div className="p-4"><p className="text-xs text-muted-foreground">{localized(p, "neighborhood", locale)}</p><h3 className="my-2 font-bold">{localized(p, "title", locale)}</h3><p className="text-accent">{localized(p, "priceLabel", locale)}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2"><Link href={`/properties/${p.id}`} className="text-xs font-bold text-accent">{t("التفاصيل", "Details")} →</Link><a href={p.sourceUrl} target="_blank" rel="noreferrer" className="text-xs font-bold text-accent">{t("الإعلان الأصلي", "Official listing")} ↗</a></div></div></div></Popup></Marker>)}</MapContainer>{!results.length && <div className="absolute inset-0 z-[1000] grid place-items-center bg-[#172329]/60 p-5"><div className="site-card p-8 text-center"><p>{t("لا توجد عقارات مطابقة", "No matching properties")}</p><button type="button" onClick={reset} className="site-button mt-4 px-5 py-2 text-xs">{t("إعادة الضبط", "Reset filters")}</button></div></div>}</div>}
    </div>
  </main>;
}