import { useState } from "react";
import { Link, useParams } from "wouter";
import { ArrowUpLeft, Bath, Bed, Check, Heart, MapPin, Phone, Share2, Square } from "lucide-react";
import { MapContainer, Marker, TileLayer } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import L from "leaflet";
import { useSiteContent, useSiteValue } from "@/data/siteContent";
import { localized, usePreferences } from "@/lib/preferences";
import { BrandLogo } from "@/components/BrandLogo";

delete (L.Icon.Default.prototype as { _getIconUrl?: unknown })._getIconUrl;
L.Icon.Default.mergeOptions({ iconRetinaUrl: "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon-2x.png", iconUrl: "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon.png", shadowUrl: "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-shadow.png" });

export default function PropertyDetail() {
  const { id } = useParams<{ id: string }>();
  const { data, isLoading, isError, refetch } = useSiteContent();
  const { locale, t } = usePreferences();
  const phone = useSiteValue("contact.phone", "8002450000");
  const property = data?.properties.find(p => p.id === id);
  const [favorite, setFavorite] = useState(false);
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  if (isLoading) return <main className="site-container min-h-[70dvh] animate-pulse py-24"><div className="h-96 bg-muted" /><div className="mt-10 h-8 w-2/3 bg-muted" /></main>;
  if (isError) return <main className="site-container min-h-[60dvh] py-32 text-center"><p>{t("تعذر تحميل العقار.", "Could not load the property.")}</p><button onClick={() => void refetch()} className="site-button mt-6 px-7 py-3">{t("إعادة المحاولة", "Try again")}</button></main>;
  if (!property) return <main className="site-container min-h-[60dvh] py-32 text-center"><h1 className="site-display text-3xl">{t("العقار غير موجود", "Property not found")}</h1><Link href="/properties" className="site-button mt-8 inline-block px-7 py-3">{t("العودة للعقارات", "Back to properties")}</Link></main>;
  const gallery = property.gallery?.length ? property.gallery : [property.image];
  const image = selectedImage ?? gallery[0];
  const title = localized(property, "title", locale);
  const amenities = locale === "en" ? property.amenitiesEn ?? [] : property.amenities;
  const share = async () => { try { if (navigator.share) await navigator.share({ title, url: window.location.href }); else { await navigator.clipboard.writeText(window.location.href); setCopied(true); window.setTimeout(() => setCopied(false), 2500); } } catch { /* dismissed */ } };
  return <main className="site-shell flex-1 pb-24">
    <div className="site-container flex items-center gap-3 py-5 text-xs text-muted-foreground"><Link href="/" className="hover:text-accent">{t("الرئيسية", "Home")}</Link><span>/</span><Link href="/properties" className="hover:text-accent">{t("العقارات", "Properties")}</Link><span>/</span><span className="truncate text-foreground">{title}</span></div>
    <div className="site-always-dark relative h-[500px] overflow-hidden bg-[#172329] text-[#f0ebdf] md:h-[680px]"><img src={image} alt={title} className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#11191d]/90 via-transparent to-transparent" /><div className="site-container absolute inset-x-0 bottom-0 pb-10 md:pb-14"><span className="border border-[#d8b675] px-3 py-1.5 text-xs text-[#d8b675]">{localized(property, "type", locale)}</span><h1 className="site-display mt-6 max-w-4xl text-3xl md:text-6xl">{title}</h1><p className="mt-4 flex items-center gap-2 text-sm text-[#f0ebdf]/80"><MapPin size={17} className="text-[#d8b675]" />{localized(property, "neighborhood", locale)}، {localized(property, "city", locale)}</p><div className="mt-6 flex gap-2"><button type="button" aria-label={favorite ? t("إزالة من المفضلة", "Remove from favorites") : t("إضافة للمفضلة", "Add to favorites")} aria-pressed={favorite} onClick={() => setFavorite(!favorite)} className="flex h-10 w-10 items-center justify-center border border-[#f0ebdf]/50 bg-[#11191d]/40"><Heart size={17} className={favorite ? "fill-[#d8b675] text-[#d8b675]" : ""} /></button><button type="button" onClick={() => void share()} aria-label={t("مشاركة العقار", "Share property")} className="flex h-10 items-center gap-2 border border-[#f0ebdf]/50 bg-[#11191d]/40 px-3"><Share2 size={17} />{copied && <span className="text-xs">{t("تم نسخ الرابط", "Link copied")}</span>}</button></div></div></div>
    <div className="site-container grid gap-14 pt-14 lg:grid-cols-[minmax(0,1.7fr)_minmax(300px,.75fr)] lg:gap-20">
      <div className="space-y-16">
        <div className="grid gap-7 border-b border-[var(--line-soft)] pb-9 sm:grid-cols-[1fr_auto] sm:items-end"><div><p className="site-eyebrow">{property.purpose === "sale" ? t("سعر البيع", "ASKING PRICE") : t("الإيجار السنوي", "ANNUAL RENT")}</p><p className="mt-4 text-3xl font-bold text-accent" dir={locale === "en" ? "ltr" : undefined}>{localized(property, "priceLabel", locale)}</p></div><div className="flex gap-7 text-xs text-muted-foreground">{[{ Icon: Bed, value: property.rooms || "—", label: t("غرف", "Beds") }, { Icon: Bath, value: property.bathrooms || "—", label: t("حمامات", "Baths") }, { Icon: Square, value: property.area || "—", label: t("م²", "m²") }].map(({ Icon, value, label }, i) => <div key={i} className="flex flex-col gap-2"><Icon size={19} className="text-accent" /><span className="text-lg font-semibold text-foreground">{value}</span><span>{label}</span></div>)}</div></div>
        <section><span className="site-eyebrow">{t("التفاصيل", "THE DETAILS")}</span><h2 className="site-display mt-5 text-3xl">{t("وصف العقار", "About this property")}</h2><p className="mt-6 whitespace-pre-line text-base leading-[2.2] text-muted-foreground">{localized(property, "description", locale)}</p></section>
        {gallery.length > 1 && <section><h2 className="site-display mb-7 text-3xl">{t("صور العرض", "Gallery")}</h2><div className="grid grid-cols-3 gap-3">{gallery.map((src, i) => <button type="button" key={src} onClick={() => setSelectedImage(src)} aria-label={t(`عرض الصورة ${i + 1}`, `View image ${i + 1}`)} aria-pressed={src === image} className={`aspect-[4/3] overflow-hidden border-2 ${src === image ? "border-accent" : "border-transparent"}`}><img src={src} alt={`${title} ${i + 1}`} loading="lazy" className="h-full w-full object-cover" /></button>)}</div></section>}
        <section><h2 className="site-display mb-7 text-3xl">{t("المميزات والمرافق", "Features and amenities")}</h2><div className="grid gap-3 sm:grid-cols-2">{amenities.map((amenity, i) => <div key={i} className="flex items-center gap-3 border-b border-[var(--line-soft)] py-3 text-sm"><Check size={16} className="text-accent" />{amenity}</div>)}</div></section>
        <section><h2 className="site-display mb-7 text-3xl">{t("الموقع على الخريطة", "Location on map")}</h2><div className="h-[390px] overflow-hidden border border-border"><MapContainer center={property.coordinates} zoom={15} style={{ height: "100%", width: "100%" }}><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png" /><Marker position={property.coordinates} /></MapContainer></div></section>
      </div>
      <aside><div className="site-always-dark sticky top-28 bg-[#172329] p-7 text-[#f0ebdf] md:p-9"><BrandLogo className="mb-8 h-16 w-16" label={t("شعار العبنق", "Alabnq logo")} /><span className="site-eyebrow">{t("نحن هنا للمساعدة", "HERE TO HELP")}</span><h3 className="site-display mt-5 text-2xl">{t("مهتم بهذا العقار؟", "Interested in this property?")}</h3><p className="mt-4 text-sm leading-8 text-[#eee8db]/70">{t("تواصل معنا لترتيب زيارة ومناقشة التفاصيل.", "Contact us to arrange a viewing and discuss the details.")}</p><div className="mt-8 space-y-3"><Link href="/contact" className="site-button flex min-h-13 items-center justify-between px-5 text-sm font-bold">{t("طلب موعد للزيارة", "Request a viewing")} <ArrowUpLeft size={17} /></Link><a href={`tel:${phone.replace(/[^\d+]/g, "")}`} className="flex min-h-13 items-center gap-3 border border-[#eee8db]/30 px-5 text-sm"><Phone size={16} />{t("اتصل بنا مباشرة", "Call us directly")}</a><a href={property.sourceUrl} target="_blank" rel="noreferrer" className="flex min-h-13 items-center justify-between border border-[#eee8db]/30 px-5 text-sm">{t("الإعلان الأصلي", "Original listing")} <ArrowUpLeft size={17} /></a></div><div className="mt-8 flex justify-between border-t border-[#eee8db]/20 pt-5 text-xs"><span className="text-[#eee8db]/60">{t("رقم المرجع", "Reference")}</span><span dir="ltr">{property.id.toUpperCase()}</span></div></div></aside>
    </div>
  </main>;
}